#!/bin/bash

function titlecase ()
{
    echo $* | sed 's/.*/\L&/; s/[a-z]*/\u&/g'
}
MODULES=$(grep "^include" modules.mk | cut -f2 -d' ' | cut -f1 -d'/')
for MODULE in $MODULES; do
    echo "Processing module '$MODULE'..."
    MODULENAME=$(titlecase $MODULE)
    if [ ! -f docs/Module/$MODULENAME.md ]; then
        echo "Creating docs/Module/$MODULENAME.md..."
        gridlabd --modhelp=md $MODULE > docs/Module/$MODULENAME.md 2>&1 || rm docs/Module/$MODULENAME.md 
        if [ -f docs/Module/$MODULENAME.md -a ! -d docs/Module/$MODULENAME ]; then
            mkdir docs/Module/$MODULENAME
        fi
    fi
    CLASSES=$(gridlabd --modhelp $MODULE | grep ^class | cut -f2 -d' ')
    for CLASS in $CLASSES; do
        CLASSNAME=$(titlecase $CLASS)
        if [ ! -f docs/Module/$MODULE/$CLASSNAME.md ]; then
            echo "Creating docs/Module/$MODULENAME/$CLASSNAME.md..."
            gridlabd --modhelp=md $MODULE:$CLASS > docs/Module/$MODULENAME/$CLASSNAME.md 2>&1 || rm docs/Module/$MODULENAME/$CLASSNAME.md 
        fi
    done
done
