#!/bin/bash
#
# Find dependencies
#

if [ "$1" == "-i" ]; then
	shift 1
	FILES=$*
elif [ "$1" == "-d" ]; then
	FILES="$*":
else
	FILES=
fi
for F in "$*"; do
	LIST=$(g++ -E $F 2>/dev/null | grep '^# ' | cut -f2 -d'"' | sort -u | grep "^${F%/*}/" )
	for G in $LIST; do
		if [ "$G" != "$F" ]; then
			FILES+=" $G"
		fi
	done
done
echo $FILES | tr ' ' '\n' | sort -u | tr '\n' ' '
echo ""
