#!/bin/bash
#
# Saves data from all failed autotests reported in validate.txt (or $1)

if [ $# -eq 1 ]; then
	DIR=$1
fi
FILES=`grep '^[ESX]	' ${DIR:-validate.txt} | cut -f3 -d'	' | sed "s:$PWD/::"`
tar cvfz validate.zip.gz $FILES
