#!/usr/local/bin/python3
"""Syntax: gridlabd timezone [OPTIONS...] LOCATION

The gridlabd timezone subcommand obtains the timezone for the location given
by LOCATION, which may be in the form `LATITUDE,LONGITUDE`, `local`, or an IP
address of the form `A.B.C.D`.

OPTIONS:

  -d|--debug       output debugging output on error
  -h|--help|help   print full documentation
  -v|--verbose     output intermediate results

EXAMPLES:

The following command obtains the timezone for the current location as
determine by the IP address of the host machine:

  shell$ gridlabd timezone local
  America/Los_Angeles

The following command obtains the timezone for the location specified:

  shell$ gridlabd timezone 37.5,-122.2
  America/Los_Angeles

The following GLM directive sets the model timezone to the local timezone:

  clock
  {
	timezone ${SHELL gridlabd timezone local};
  }
"""

import sys, os

verbose = False
debug = False
location = None

E_OK = 0
E_SYNTAX = 1
E_INVALID = 2
E_FAILED = 3

def output_verbose(msg):
	if verbose:
		print(f"VERBOSE [{os.path.basename(sys.argv[0])}]: {msg}",file=sys.stderr)

def output_error(msg,code=None):
	print(f"VERBOSE [{os.path.basename(sys.argv[0])}]: {msg}",file=sys.stderr)
	if type(code) is int:
		exit(code)

def output_help():
	print(__doc__)
	exit(E_OK)

def output_syntax():
	print(__doc__.split("\n")[0])
	exit(E_SYNTAX)

try:
	from timezonefinder import TimezoneFinder
	import geocoder as gc

	if len(sys.argv) == 1:
		output_syntax()

	while len(sys.argv) > 1:
		if sys.argv[1] in ["-d","--debug"]:
			debug = True
		elif sys.argv[1] in ["-v","--verbose"]:
			verbose = True
		elif sys.argv[1] in ["-h","--help","help"]:
			output_help()
		elif sys.argv[1][0] == '-':
			output_error(f"option '{sys.argv[1]}' is not valid",E_SYNTAX)
		else:
			location = sys.argv[1]
		del sys.argv[1]

	if not location:
		output_error("no location specified",E_SYNTAX)
	elif location == 'local':
		latlon = gc.ip('me').latlng
	elif location.find(",") > 0:
		latlon = list(map(lambda x:float(x),location.split(",")))
	else:
		latlon = gc.ip(location).latlng
	if not type(latlon) is list or len(latlon) != 2 \
			or type(latlon[0]) != float or type(latlon[1]) != float:
		output_error("latlon format is not valid",E_INVALID)
	output_verbose(f"latlon = {latlon}")

	print(TimezoneFinder().timezone_at(lat=latlon[0],lng=latlon[1]),file=sys.stdout)

	exit(E_OK)

except Exception as err:

	if debug:
		raise
	else:
		output_error(str(err),E_FAILED)
