#!/bin/bash

EXE="$0"
function error()
{
	echo "$EXE: $*"
}

function help()
{
	cat <<-END
		Syntax: gridlabd version <command> <options...>
		Commands:
		  help              get this list of commands
		  show              show the current active version
		  set [<pattern>]   set the active version
		  list [<pattern>]  get a list of available versions
	END
}

function set()
{
	ln -sf /usr/local/opt/gridlabd/*$1* /usr/local/opt/gridlabd/current
	for F in bin lib share include; do
		[ ! -f /usr/local/$F/gridlabd ] ln -sf /usr/local/opt/gridlabd/current/$F/gridlabd /usr/local/$F/gridlabd
	done
	[ ! -f /usr/local/bin/gridlabd.bin ] && ln -sf /usr/local/opt/gridlabd/current/bin/gridlabd.bin /usr/local/bin/gridlabd.bin
}

function show()
{
	basename /usrlocal/opt/gridlabd/current
}

function list()
{
	if [ $# -eq 0 ]; then
		basename /usr/local/opt/gridlabd/* | grep -v '^current$'
	else
		basename /usr/local/opt/gridlabd/*$1*
	fi
}

if [ $# -eq 0 ]; then
	help
	exit 1
fi

case "$1" in 
	(help) 
		help 
		;;
	(get) 
		get 
		;;
	(show) 
		shift 1
		set $* 
		;;
	(list) 
		shift 1
		list $* 
		;; 
	(*)
		error "$1 is not a valid command"
		;;
esac
