#!/usr/local/bin/python3

import sys
import json

def error(msg):
    print("ERROR: %s" % (msg), file=sys.stderr)

try:
    data = json.load(sys.stdin)
    if len(sys.argv) > 1 :
        for item in sys.argv[1::]:
            print(data[item])
    else:
        print(json.dumps(data,indent=4))
except:
    error("%s %s" % (sys.exc_info()[0],sys.exc_info()[1]))
    quit(1)