#!/usr/local/bin/python3
"""gridlabd-openfido subcommand
"""

import sys, os

sys.path.append("/usr/local/src/gridlabd")
sys.path.append(os.getenv("HOME")+"/.gridlabd")
sys.path.append(".")
sys.path.append(sys.argv[0].replace("gldcore/scripts/gridlabd-openfido","python_extras"))

import openfido

def poutput(msg,exit=None):
    """Print an output message

    Outputs messages regardless of quiet or verbose setting
    """
    print(msg,file=sys.stdout,flush=True)
    if exit:
        sys.exit(exit)

def pverbose(msg,exit=None):
    """Print a verbose output message

    Outputs messages if verbose is enabled
    """
    if config.verbose:
        print(msg,file=sys.stdout,flush=True)
    if exit:
        sys.exit(exit)

def pquiet(msg,exit=None):
    """Print a quiet output message

    Outputs messages if quiet is not enabled
    """
    if not config.quiet:
        print(msg,file=sys.stdout,flush=True)
    if exit:
        sys.exit(exit)

def pwarning(msg,exit=None):
    """Print a warning message

    Warning messages are suppressed by the quiet option
    """
    if not config.quiet:
        print(f'WARNING [openfido]: {msg}',file=sys.stderr,flush=True)
    if exit:
        sys.exit(exit)

def perror(msg,exit=None):
    """Print an error message

    Error messages are suppressed by the quiet option
    """
    if not config.quiet:
        print(f'ERROR [openfido]: {msg}',file=sys.stderr,flush=True)
    if exit:
        sys.exit(exit)

default_streams = { "output" :  poutput,
                    "warning" : pwarning,
                    "error" :   perror,
                    "verbose" : pverbose,
                    "quiet" :   pquiet,
                    }
                    

# openfido_config import
try: 
    import openfido_config as config
except:
    # default options
    class config:
        """Configuration options
        """
        verbose = False # print more messages as work is done
        quiet = False # print fewer messages as work is done
        orgname = "https://github.com/openfido" # default repo for workflows and pipelines
        branch = "master" # default branch to use when downloading workflows and pipelines
        cache = "/usr/local/share/gridlabd/openfido" # additional path for downloaded modules
    pass

# setup default streams
if not hasattr(config,"streams"):
    config.streams = {}
for name, value in default_streams.items():
    if not name in config.streams:
        config.streams[name] = value
    elif not callable(config.streams[name]):
        raise Exception(f"config.streams['{name}'] is not callable")

sys.path.append(config.cache)

def main(*args):
    """gridlabd-openfido main function"""
    execname = args[0]
    n = 1
    while len(args) > n and args[n][0] == '-':
        if args[n] in ['-v','--verbose']:
            config.verbose = True
        elif args[n] in ['q','--quiet']:
            config.quiet = True
        else:
            perror(f"command option '{args[n]}' is not valid")
        n += 1
    if len(args) > n:
        command = args[n]
        if len(sys.argv) > n+1:
            options = args[n+1:]
        else:
            options = []
    else:
        command = "help"
        options = []
    if hasattr(openfido,command):
        try:
            call = getattr(openfido,command)
            call(options=options,stream=config.streams)
        except Exception as err:
            perror(err)
            pass
    else:
        perror(f"'{command}' is not a valid command",exit=1)

if __name__ == "__main__":
    main(sys.argv)
