#!/bin/bash

if [ "$1" == "help" ]; then
	echo "Syntax: gridlabd help [command]"
	exit 0
elif [ -f "$GLD_BIN/gridlabd-$1" ]; then
	"$GLD_BIN/gridlabd-$1" help
fi

L="$( cd $GLD_BIN ; ls -1d gridlabd-* )"

echo "Syntax: gridlabd command [options] ..."
echo "Commands:"
for F in $L ; do
	if [ ! "$F" == "help" ]; then
		$GLD_BIN/$F help | grep 'Syntax: ' | sed -e 's/Syntax: gridlabd/ /'
	fi
done