Resources:
  RDSCluster:
    Type: 'AWS::RDS::DBCluster'
    Properties:
      Engine: aurora
      DatabaseName: myDatabase
      MasterUsername: masterUsername
      MasterUserPassword: masterUserPassword
      VpcSecurityGroupIds:
        - !GetAtt LambdaSecurityGroup.GroupId
      BackupRetentionPeriod: 3

  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow lambda access to RDS
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        SourceSecurityGroupId:
          Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
