#!/bin/bash

EXE="$0"
CNF="${EXE/-status/.cnf}"
source "${EXE/-status/-util}"

while [ $# -gt 0 ]; do
	case "$1" in
	("-h"|"--help")
		cat <<END
Syntax: $0 [options]
Options:
  -h|--help    output this help text
  -l|--logs    display the logs 
END
		exit
		;;
	("-l"|"--logs")
		shift
		docker logs $NAME
		;;
	(*)
		error 1 "option '$1' is invalid"
	esac
done

STATUS="$(docker inspect -f '{{.State.Health.Status}}' $NAME)"
if [ -z $STATUS ]; then
	error 2 "$NAME not found"
else
	echo "$NAME is $(docker inspect -f '{{.State.Health.Status}}' $NAME)"
fi
