dist_pkgdata_DATA += gldcore/geodata/geodata_address.py
dist_pkgdata_DATA += gldcore/geodata/geodata_census.py
dist_pkgdata_DATA += gldcore/geodata/geodata_distance.py
dist_pkgdata_DATA += gldcore/geodata/geodata_elevation.py
dist_pkgdata_DATA += gldcore/geodata/geodata_powerline.py
dist_pkgdata_DATA += gldcore/geodata/geodata_powerline_cabletypes.csv
# dist_pkgdata_DATA += gldcore/geodata/geodata_transportation.py
dist_pkgdata_DATA += gldcore/geodata/geodata_utility.py
dist_pkgdata_DATA += gldcore/geodata/geodata_vegetation.py
dist_pkgdata_DATA += gldcore/geodata/geodata_weather.py
