FROM public.ecr.aws/lambda/python:3.10

RUN yum update -y && yum install -y postgresql-devel

COPY ./cloud/websites/version.gridlabd.us/lambda/requirements.txt .
RUN pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

COPY ./cloud/websites/version.gridlabd.us/lambda/app.py ${LAMBDA_TASK_ROOT}

ARG HANDLER
CMD [ "${HANDLER}" ]
