#!/bin/bash
"exec" "`dirname $0`/python3" "$0" "$@"

import sys
import json

input_file = sys.stdin
output_file = sys.stdout

def error(code,msg):
    print("ERROR %d: %s" % (code,msg), file=sys.stderr);
    exit(code);

def output_json(data):
    if type(data) is dict or type(data) is list :
        print(json.dumps(data,indent=4),file=output_file)
    else:
        print(data,file=output_file)

def output_raw(data):
    print(data,file=output_file)

def output_csv(data):
    if type(data) is dict:
        for key,value in data.items():
            print(f"{key},{value}",file=output_file)
    elif type(data) is list:
        print("\n".join(data),file=output_file)
    else:
        print(data,file=output_file)

output_format = output_json
keys = []
keys_only = False

if len(sys.argv) > 1 and sys.argv[1] in ['-h','--help','help'] :
    print("Syntax: gridlabd json-get [keys ...] [-k|--keys] [-j|--json|-r|--raw|-r|--csv] [-i|--input INTPUT] [-o|--output OUTPUT]");
    quit(0);
try:
    if len(sys.argv) > 1 :
        n = 1
        while n < len(sys.argv):
            item = sys.argv[n]
            if item in ['-k','--keys'] :
                keys_only = True
            elif item in ['-r','--raw']:
                output_format = output_raw
            elif item in ['-j','--json']:
                output_format = output_json
            elif item in ['-c','--csv']:
                output_format = output_csv
            elif item in ['-i','--input']:
                input_file = open(sys.argv[n+1],'r')
                n += 1
            elif item in ['-o','--output']:
                output_file = open(sys.argv[n+1],'w')
                n += 1
            else:
                keys.append(item)
            n += 1
        data = json.load(input_file);
        for key in keys:
            if type(data) is dict and key in data.keys() :
                data = data[key];
            elif type(data) is list and int(key) >=0 and int(key) <= len(data) :
                data = data[int(key)];
            else :
                error(2,"%s is not valid"%key);
        if keys_only:
            data = list(data.keys())
    output_format(data)
except:
    error(1,"%s %s" % (sys.exc_info()[0],sys.exc_info()[1]));
