#!/bin/bash

if [ "$1" == "help" ]; then
	echo "Syntax: gridlabd python"
	${GLD_BIN:-/opt/gridlabd/bin}/python3 --help | head -n 1 | cut -f3- -d' '
else
	${GLD_BIN:-/usr/local/opt/gridlabd/bin}/python3 $*
fi
