#!/bin/bash

EXE="$(basename $0)"
BIN=${0/-version/.bin}

function error()
{
	RC=$1
	shift 1
	echo "ERROR [$EXE] $*" > /dev/stderr
	exit $RC
}

function warning()
{
	echo "WARNING [$EXE] $*" > /dev/stderr
}

case "$1" in
--dryrun)
	ACTION="echo"
	shift 1
	;;
--*)
	error 9 "'$1' in an invalid option"
	;;
*)
	ACTION=""
	;;
esac

function version-help()
{
	cat <<-END
		Syntax: gridlabd version [--dryrun] <command> <options...>
		Commands:
		  help                    get this list of commands
		  check [-v|-q|-w]        check for a newer version
		    -v                      enable verbose output
		    -q                      disable all output
		    -w                      only output warnings and errors and log check result
		  list [<pattern>]        get a list of available versions
		  show                    show the current active version
		  set [<pattern>]         set the active version
		  source                  open source code of the active version
		  delete [-a|<pattern>]   delete versions
		    -a                      delete all version except current one
	END
}

function version-check()
{
	version=$(${BIN} --version)
	branch=$(${BIN} --version=git-branch)
	if [ $(git remote | wc -l) -gt 1 ]; then
		warning "more than 1 git remote found, using '$(git remote | head -n 1)' for version check"
	fi
	origin=$(git remote get-url $(git remote | head -n 1) | cut -f4- -d/ | cut -f1 -d. )
	remote=$( (curl -sL "https://raw.githubusercontent.com/$origin/$branch/source/version.h" | grep '#define REV_' | cut -f3 -d' ' | tr '\n' . | cut -f-3 -d.) || echo "none" )
	if [ "$remote" == "none" -o -z "$remote" ]; then
		[ "$1" != "-q" -a "$1" != "-w" ] && error 2 "$version ($branch) branch not found on github"
		[ "$1" != "-q" ] && warning "$version ($branch) branch not found on github"
		exit 0
	fi
	[ "$1" == "-v" ] && echo "REMOTE/$branch $remote"
	${BIN} --version="-ge $remote" 2>/dev/null || ( ( [ "$1" != "-q" -a "$1" != "-w" ] && warning "$version ($branch) is outdated" ) ; exit 0 )
	[ "$1" != "-q" -a "$1" != "-w" ] && echo "$version ($branch) is ok"
	[ "$1" == "-w" ] && ( curl -sL "http://version.gridlabd.us/index.html?v=${version}&b=${branch}" >/dev/null & )
	exit 0
}

function version-source()
{
	open $(${BIN} git commit HEAD html_url | sed -e 's:/commit/:/tree/:')
}

function version-save()
{
	if [ -f /usr/local/bin/gridlabd -a ! -L /usr/local/bin/gridlabd ]; then
		SAVED="$(${BIN} --version | cut -f2 -d' ')-saved_$(date '+%Y%m%d')"
		N=0
		TRY="$SAVED"
		while [ -d /usr/local/opt/gridlabd/$TRY ]; do
			TRY="$SAVED-$N"
			N=$(($N+1))
		done
		SAVED="$TRY"
		$ACTION mkdir -p /usr/local/opt/gridlabd/$SAVED/{bin,lib,share,include}
		for F in bin lib share include; do
			[ ! -d /usr/local/opt/gridlabd/$SAVED/$F ]; $ACTION mkdir -p /usr/local/opt/gridlabd/$SAVED/$F
			if [ "$F" == "bin" ]; then
				$ACTION mv /usr/local/bin/gridlabd* /usr/local/opt/gridlabd/$SAVED/bin
			else
				[ -f /usr/local/$F/gridlabd -a ! -L /usr/local/$F/gridlabd ] && $ACTION mv /usr/local/$F/gridlabd /usr/local/opt/gridlabd/$SAVED/$F
			fi
		done
	fi
}

function version-set()
{
	version-save
	L="$1"
	if [ ! -d "/usr/local/opt/gridlabd/$L" ]; then
		L=$(cd /usr/local/opt/gridlabd ; ls -1d *$1* | grep -v current)
	fi
	if [ -z "$L" ]; then
		L="$(${BIN} --version=name | sed -e 's/^gridlabd-//')"
	elif [ "$(echo $L | wc -w)" -gt 1 ]; then
		error 2 "ambiguous version"
	fi
	if [ ! "$(readlink /usr/local/opt/gridlabd/current)" == "/usr/local/opt/gridlabd/$L" ]; then
		$ACTION rm -f /usr/local/opt/gridlabd/current
		$ACTION ln -s /usr/local/opt/gridlabd/$L /usr/local/opt/gridlabd/current
	fi
	for F in bin lib share include; do
		if [ ! "$(readlink /usr/local/$F/gridlabd)" == "/usr/local/opt/gridlabd/current/$F/gridlabd" ]; then
			$ACTION rm -rf /usr/local/$F/gridlabd
			$ACTION ln -s /usr/local/opt/gridlabd/current/$F/gridlabd /usr/local/$F/gridlabd
		fi
	done
	echo "$L"
}

function version-show()
{
	if [ -L /usr/local/opt/gridlabd/current ]; then
		basename $(readlink /usr/local/opt/gridlabd/current)
	else
		echo "Current version is custom installed"
	fi
}

function version-delete()
{
	if [ "$1" == "-a" ]; then
		L="$(ls -1 /usr/local/opt/gridlabd | grep -v current)"
	else
		L="$1"
		if [ ! -d "$L" ]; then
			L=$(cd /usr/local/opt/gridlabd ; ls -1d *$1* | grep -v current)
		fi
	fi
	if [ ! -z "$L" ]; then
		for F in $L; do
			[ ! "$F" == "current" -a -d "/usr/local/opt/gridlabd/$F" -a ! "$(readlink /usr/local/opt/gridlabd/current)" == "/usr/local/opt/gridlabd/$F" ] && $ACTION rm -rf /usr/local/opt/gridlabd/$F
		done
	fi
}

function version-list()
{
	if [ $# -eq 0 ]; then
        for D in $(basename /usr/local/opt/gridlabd/*); do
            if [ "$D" != "current" -a -x "/usr/local/opt/gridlabd/$D/bin/gridlabd.bin" ]; then
                echo $D
            fi
        done
	elif [ "$1" == "-l" ]; then
        longlist $2
    else
        for D in $(basename /usr/local/opt/gridlabd/*$1*); do
            if [ "$D" != "current" -a -x "/usr/local/opt/gridlabd/$D/bin/gridlabd.bin" ]; then
                echo $D
            fi
        done
	fi
}

function longlist()
{
    if [ $# -eq 0 ]; then
		LIST=$(basename /usr/local/opt/gridlabd/* | grep -v '^current$')
	else
		LIST=$(basename /usr/local/opt/gridlabd/*$1*)
	fi
    echo "total$(du -sh /usr/local/opt/gridlabd | cut -c1-4)"
    for D in $LIST; do
        if [ -x "/usr/local/opt/gridlabd/$D/bin/gridlabd.bin" ]; then
            NAME=$(basename $D)
            VERSION=$(echo $NAME | cut -f1 -d-)
            BUILD=$(echo $NAME | cut -f2 -d-)
            BRANCH=$(echo $NAME | cut -f3 -d-)
            SIZE=$(du -sh /usr/local/opt/gridlabd/$D | cut -c1-4)
            echo "$VERSION $BUILD $SIZE $BRANCH"
        fi
    done
}

if [ $# -eq 0 ]; then
	version-show
	exit 0
fi

if [ "$(type -t version-$1)" == "function" ]; then
	version-$*
else
	error 9 "'$1' is not a valid command"
fi

if [ -z "$(which gridlabd)" ]; then
	warning "gridlabd is not in the current PATH environment"
fi
if [ ! -x "/usr/local/bin/python3" ]; then
	warning "python3 is not linked where gridlabd wants it in /usr/local/bin"
fi

