#!/bin/bash
if [ $# -gt 0 -a "$1" == "help" ]; then
    echo "Syntax: gridlabd requirements"
    exit 0
fi
for REQ in $(find . -name requirements.txt -print); do
    /usr/local/bin/python3 -m pip --disable-pip-version-check install -q -r $REQ
done
