#!/bin/bash
# Syntax: python [OPTIONS ...] -c COMMAND | -m MODULE | FILE | - [ARGUMENTS ...]
if [ "$1" == "help" ]; then
	echo -n 'Syntax: gridlabd python [OPTIONS ...] -c COMMAND | -m MODULE | FILE | - [ARGUMENTS ...]'
else
	/usr/local/bin/python3 $*
fi
