#!/bin/bash

PYTHON_LOC="$(dirname $0)/python3"
QUIET="-q"
STDOUT="/dev/null"
STDERR="/dev/null"

if [ $# -eq 0 ]; then
    $PYTHON_LOC -m pip freeze
    exit 0
fi

while [ $# -gt 0 ]; do
    if [ "$1" == "--requirements" -o "$1" == "-r" ]; then
        shift 1
        $PYTHON_LOC -m pip $QUIET install -r $1 
    elif [ "$1" == "--verbose" -o "$1" == "-v" ]; then
        QUIET=""
        STDERR="/dev/stderr"
        STDOUT="/dev/stdout"
    else
        $PYTHON_LOC -m pip freeze | grep $1 1>$STDOUT 2>$STDERR || $PYTHON_LOC -m pip $QUIET install $1 
        test "$($PYTHON_LOC -m pip freeze | grep ^$1)" != "" || exit 1 
    fi
    shift 1
done
exit 0
