#!/bin/bash
# Syntax: help [COMMAND]

if [ $# -gt 0 ]; then
	if [ "$1" == "help" ]; then
		echo "Syntax: gridlabd help [ SUBCOMMAND | TOOL ]"
		exit 0
	elif [ -f "$GLD_BIN/gridlabd-$1" ]; then
		"$GLD_BIN/gridlabd-$1" --help
	elif [ -f "$GLD_ETC/$1.py" ]; then
		python3 $GLD_ETC/$1.py --help
	else
		echo "ERROR: subcommand or tool '$1' not found"
	fi
else
	gridlabd --help
	echo ""
	echo "Subcommands"
	echo "-----------"
	for F in $( cd $GLD_BIN ; ls -1d gridlabd-* ) ; do
		head -n 4 $GLD_BIN/$F | grep '^# Syntax: ' | sed -e 's/^# Syntax: /  /'
	done
	echo ""
	echo "Tools"
	echo "-----"
	for F in $( cd $GLD_ETC ; ls -1d *.py | grep -v '^gridlabd-' ) ; do
		head -n 4 $GLD_ETC/$F | grep '^# Syntax: ' | sed -e 's/^# Syntax: /  /'
	done

fi