#!/bin/bash

EXE="$0"
function error()
{
	echo "$EXE: $*"
}

function help()
{
	cat <<-END
		Syntax: gridlabd version <command> <options...>
		Commands:
		  help              get this list of commands
		  show              show the current active version
		  set [<pattern>]   set the active version
		  list [<pattern>]  get a list of available versions
	END
}

function set()
{

#	if [ ! -d /usr/local/]

	# upgrade from older version
	SAVENAME="gridlabd-$(date '+%y%m%d_%H%M%S')"

	# set main script
	if [ -e /usr/local/bin/gridlabd -a ! -L /usr/local/bin/gridlabd ]; then
		mkdir -p /usr/local/$SAVENAME/bin
		mv /usr/local/bin/gridlabd /usr/local/$SAVENAME/bin/
		ln -s /usr/local/gridlabd/bin/gridlabd /usr/local/bin/gridlabd
	fi
	if [ -e /usr/local/lib/gridlabd -a ! -L /usr/local/lib/gridlabd ]; then
		mkdir -p /usr/local/$SAVENAME/lib
		mv /usr/local/lib/gridlabd /usr/local/$SAVENAME/lib
		ln -s /usr/local/gridlabd/lib/gridlabd /usr/local/lib/gridlabd
	fi
	if [ -e /usr/local/share/gridlabd -a ! -L /usr/local/share/gridlabd ]; then
		mkdir -p /usr/local/$SAVENAME/share
		mv /usr/local/share/gridlabd /usr/local/$SAVENEMT/share
		ln -s /usr/local/gridlabd/share/gridlabd /usr/local/share/gridlabd
	fi
	ln -s /usr/local/$1
}

function show()
{
	if [ ! -x /usr/local/bin/gridlabd ]; then
		error "no active gridlabd version found"
	fi
}

function list()
{
	if [ $# -eq 0 ]; then
		(cd /usr/local ; ls -1d gridlabd-*)
	else
		(cd /usr/local ; ls -1d /usr/local/gridlabd-*$1*)
	fi
}

if [ $# -eq 0 ]; then
	help
	exit 1
fi

case "$1" in 
	(help) 
		help 
		;;
	(get) 
		get 
		;;
	(show) 
		shift 1
		set $* 
		;;
	(list) 
		shift 1
		list $* 
		;; 
	(*)
		error "$1 is not a valid command"
		;;
esac
