version: '3.7'
services:

  ### MYSQL
  # mysql:
  #   image: mysql
  #   build:
  #     context: .
  #     dockerfile: DockerFile-mysqld
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ../..:/usr/local/src/gridlabd
  #   environment:
  #     MYSQL_ROOT_PASSWORD: gridlabd

  mysql:
    image: mysql/mysql-server:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: gridlabd

#  ### APACHE
#  httpd:
#    image: httpd:latest
#    ports:
#      - "80:80"
#    volumes:
#      - ../..:/usr/local/src/gridlabd
#    #init: true

#  ### GRIDLABD
#  gridlabd:
#    image: gridlabd/slac-master:latest
#    ports:
#      - "6266-6999:6266-6999"
#    #init: true
