version: '3.7'
services:

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'gridlabd'
      MYSQL_USER: 'gridlabd'
      MYSQL_ROOT_PASSWORD: 'gridlabd'
    volumes:
      - gridlabd-db:/var/lib/mysql

  gridlabd:
    image: gridlabd/slac-master:latest
    ports:
      - "6266-6299:6266-6299"

volumes:
  gridlabd-db:


#  ### APACHE
#  httpd:
#    image: httpd:latest
#    ports:
#      - "80:80"
#    volumes:
#      - ../..:/usr/local/src/gridlabd
#    #init: true

#  ### GRIDLABD
#  gridlabd:
#    image: gridlabd/slac-master:latest
#    ports:
#      - "6266-6999:6266-6999"
#    #init: true
