import sys
import pandas

def convert(input_file, output_file, options={}):
    """Convert a CSV data table to a GLM library object list

    ARGUMENTS

        input_file (str) - input file name (csv file)

        ouput_file (str) - output file name (glm file)
    
    RETURNS

        None
    """
    table = pandas.read_csv(input_file)    
    with open(output_file,"wt") as fh:
        print(f"// generated by csv-table2glm-library.py -i")
        for id, data in table.iterrows():
            print(id,data,file=fh)

