name: C/C++ CI

on:
  push:
    branches: [ master develop ]
  pull_request:
    branches: [ master develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: autoconf
      run: ./autoreconf -isf
    - name: configure
      run: ./configure
    - name: make
      run: make -j10 system
    - name: validate
      run: gridlabd --validate
